CREATE TABLE USERS (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(60),
  EMAIL VARCHAR(60),
  PASSWORD VARCHAR(100)
)

CREATE TABLE STEMS (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(60),
  CREATE_USER_ID VARCHAR(60),
  CREATED_TIME DATE,
  UPDATE_USER_ID VARCHAR(60),
  UPDATED_TIME DATE
)

CREATE TABLE BRANCHES (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(60),
  STEM_ID UUID,
  CREATE_USER_ID VARCHAR(60),
  CREATED_TIME DATE,
  UPDATE_USER_ID VARCHAR(60),
  UPDATED_TIME DATE,
  FOREIGN KEY(STEM_ID) REFERENCES STEMS(ID)
)

CREATE TABLE FRUITS (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(60),
  BRANCH_ID UUID,
  CREATE_USER_ID VARCHAR(60),
  CREATED_TIME DATE,
  UPDATE_USER_ID VARCHAR(60),
  UPDATED_TIME DATE,
  FOREIGN KEY(BRANCH_ID) REFERENCES BRANCHES(ID)
)
